apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend-jw
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: frontend-fargate-jw
  template:
    metadata:
      labels:
        app: frontend-fargate-jw
