apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 160270626841.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend-jw
  newName: 160270626841.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend-jw
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
