---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo-jw
  region: ap-northeast-2
fargateProfiles:
  - name: frontend-fargate-profile-jw
    selectors:
      - namespace: default
        labels:
          app: frontend-fargate-jw
