---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-flask-backend-hpa-jw
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-flask-backend-jw
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
